Docker Build

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -35,7 +35,14 @@ jobs:
           echo "docker_output=$docker_output" >> $GITHUB_OUTPUT
 
       - name: Test Docker Image
+        shell: bash
         env:
           docker_output: ${{ steps.docker-run.outputs.docker_output }}
         run: |
-          echo $docker_output
+          if [[ "$docker_output" == "*Hello World!*" ]]
+          then
+            echo "Docker Build Completed"
+          else
+            echo "Docker Build Failed"
+            exit 1
+          fi
